#!/bin/sh
dir=`dirname "$0"`
script="$dir/reposman/reposman.pl"


if [ -z "$*" ] ; then
	exec "$script" --checkout perl libmyplace-perl shellscript babebase firefox websaver2 gm-scripts ws
elif [ "$1" = "all" ] ; then
	exec "$script" --checkout 
else
	exec "$script" --checkout "$@"
fi

